---
- name: Create convertx directory
  ansible.builtin.file:
    path: /docker/convertx
    state: directory
    mode: '0755'

- name: Template docker compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /docker/convertx/compose.yml
    mode: '0644'

- name: Start convertx stack
  tags: start
  community.docker.docker_compose_v2:
    project_src: /docker/convertx
    state: present
    pull: always

- name: Stop convertx stack
  tags: stop
  community.docker.docker_compose_v2:
    project_src: /docker/convertx
    state: absent

- name: Update convertx stack
  tags: update
  community.docker.docker_compose_v2:
    project_src: /docker/convertx
    state: present
    pull: always

- name: Restart convertx stack
  tags: restart
  community.docker.docker_compose_v2:
    project_src: /docker/convertx
    state: restarted
