---
- name: Create homarr directory
  ansible.builtin.file:
    path: /docker/homarr
    state: directory
    mode: '0755'

- name: Template docker compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /docker/homarr/compose.yml
    mode: '0644'

- name: Start homarr stack
  tags: start
  community.docker.docker_compose_v2:
    project_src: /docker/homarr
    state: present
    pull: always

- name: Stop homarr stack
  tags: stop
  community.docker.docker_compose_v2:
    project_src: /docker/homarr
    state: absent

- name: Update homarr stack
  tags: update
  community.docker.docker_compose_v2:
    project_src: /docker/homarr
    state: present
    pull: always

- name: Restart homarr stack
  tags: restart
  community.docker.docker_compose_v2:
    project_src: /docker/homarr
    state: restarted
