---
- name: Set timezone to Europe/Brussels
  community.general.timezone:
    name: Europe/Brussels

- name: Manage authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', 'id_rsa.pub') }}"
    state: present
