---
- name: Apply common configuration to all vms
  hosts: vms
  become: true
  roles:
    - common

- name: Apply common configuration to all lxc containers
  hosts: lxc
  become: true
  roles:
    - common
