---
- name: Create immich directory
  ansible.builtin.file:
    path: /docker/immich
    state: directory
    mode: '0755'

- name: Template docker compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /docker/immich/compose.yml
    mode: '0644'

- name: Manage immich stack
  community.docker.docker_compose_v2:
    project_src: /docker/immich
    state: "{{ 'absent' if service_state == 'absent' else 'present' }}"
    restarted: "{{ service_state == 'restarted' }}"
    pulled: "{{ service_state == 'pulled' }}"
