---
- name: Create immich directory
  ansible.builtin.file:
    path: /docker/immich
    state: directory
    mode: '0755'

- name: Template docker compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /docker/immich/compose.yml
    mode: '0644'

- name: Start immich stack
  tags: start
  community.docker.docker_compose_v2:
    project_src: /docker/immich
    state: present
    pull: always

- name: Stop immich stack
  tags: stop
  community.docker.docker_compose_v2:
    project_src: /docker/immich
    state: absent

- name: Update immich stack
  tags: update
  community.docker.docker_compose_v2:
    project_src: /docker/immich
    state: present
    pull: always

- name: Restart immich stack
  tags: restart
  community.docker.docker_compose_v2:
    project_src: /docker/immich
    state: restarted
