---

- hosts: all
  become: true
  roles:
    - common

- hosts: immich
  become: true
  roles:
    - immich

- hosts: network
  become: true
  roles:
#     - pi_hole
#     - npm
    - homarr
    - convertx

- hosts: servarr
  become: true
  roles:
    - servarr
    - jellyfin
