---
- name: Create arrstack directory
  ansible.builtin.file:
    path: /docker/arrstack
    state: directory
    mode: '0755'

- name: Template docker compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /docker/arrstack/compose.yml
    mode: '0644'

- name: Start arrstack stack
  tags: start
  community.docker.docker_compose_v2:
    project_src: /docker/arrstack
    state: present
    pull: always

- name: Stop arrstack stack
  tags: stop
  community.docker.docker_compose_v2:
    project_src: /docker/arrstack
    state: absent

- name: Update arrstack stack
  tags: update
  community.docker.docker_compose_v2:
    project_src: /docker/arrstack
    state: present
    pull: always

- name: Restart arrstack stack
  tags: restart
  community.docker.docker_compose_v2:
    project_src: /docker/arrstack
    state: restarted
